name: hangman_game
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  rflutter_alert: ^2.0.7
  material_design_icons_flutter: ^7.0.7296
  sqflite: ^2.3.0
  path: ^1.8.3
  flutter_spinkit: ^5.2.0
  date_format: ^2.0.7
  intl: ^0.18.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/res/
  fonts:
    - family: PatrickHand
      fonts:
        - asset: assets/fonts/PatrickHand-Regular.ttf
    - family: FiraMono
      fonts:
        - asset: assets/fonts/FiraMono-Bold.ttf
        - asset: assets/fonts/FiraMono-Regular.ttf